# Numpy(numerical python)
pip install numpy

conda install numpy

#    Intro

In [1]:
import numpy as np #np is an alias for numpy it can be anything
print(np.__version__)

1.19.2


In [2]:
arr1 = np.array([1,2,3,4,5])#1D array
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1.min()

1

In [4]:
arr1.max()

5

In [5]:
arr1.mean()

3.0

In [6]:
arr1.sum()

15

In [7]:
arr1.std()

1.4142135623730951

In [8]:
arr1.var()

2.0

In [9]:
arr1[0]#first index of arr1 array

1

In [10]:
print(arr1[::2])#slicing

[1 3 5]


# Math Operators

In [11]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [12]:
arr1/arr1

array([1., 1., 1., 1., 1.])

In [13]:
arr1-arr1

array([0, 0, 0, 0, 0])

In [14]:
arr1*arr1

array([ 1,  4,  9, 16, 25])

In [15]:
arr1**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Data Types

In [16]:
print(arr1.dtype)#printing data type, it can be int, float, object etc.

int32


In [17]:
arrf = np.array([1,2,3,4,5], dtype="f")
print("Data type:",arrf.dtype)
print(arrf)

Data type: float32
[1. 2. 3. 4. 5.]


In [18]:
arrf2 = arrf.astype(int)
print("Data type:",arrf2.dtype)
print(arrf2)

Data type: int32
[1 2 3 4 5]


# Multidimensional arrays

In [19]:
arr0 = np.array(5)#0D Array
print(arr0)

5


In [20]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [21]:
arr2[0]

array([1, 2, 3])

ndmin

In [22]:
arr4 = np.array([1, 2, 3, 4], ndmin=5)
print(arr4)
print(arr4[0,0,0,0,3])
print("Shape:",arr4.shape)

[[[[[1 2 3 4]]]]]
4
Shape: (1, 1, 1, 1, 4)


In [23]:
print(arr1[0]+arr2[1])

[5 6 7]


In [24]:
arr5 = arr4.copy()


In [25]:
#creating a random array
a = np.random.randint(20, size=5)
a
a2 = a.copy()


In [26]:
a = np.random.randint(100, size=20)
print(a)
print("\n")
print(a2)

[20 10 93  8  3 49 94 43 41 93  4 63 84 86 38 23  9 91 31 57]


[ 2  1 14 12 16]


In [27]:
a2.flatten()#return a copy of the original array

array([ 2,  1, 14, 12, 16])

In [28]:
a3 = a2.view()
print(a3)

[ 2  1 14 12 16]


In [29]:
arr12 = np.concatenate((arr1, a))
arr12

array([ 1,  2,  3,  4,  5, 20, 10, 93,  8,  3, 49, 94, 43, 41, 93,  4, 63,
       84, 86, 38, 23,  9, 91, 31, 57])

In [30]:
arr6 = np.array([1, 2, 3])

arr7 = np.array([4, 5, 6])

arr8 = np.stack((arr6, arr7), axis=1)

print(arr8)

[[1 4]
 [2 5]
 [3 6]]


# Sorting Strings

In [31]:
st = np.array(["AB","BZ","ZB","MN","NJ","AC","AA","DD","CC","P","O","ZXZ","CD","GFGF","PIJ"])
st

array(['AB', 'BZ', 'ZB', 'MN', 'NJ', 'AC', 'AA', 'DD', 'CC', 'P', 'O',
       'ZXZ', 'CD', 'GFGF', 'PIJ'], dtype='<U4')

In [32]:
st.sort()
st

array(['AA', 'AB', 'AC', 'BZ', 'CC', 'CD', 'DD', 'GFGF', 'MN', 'NJ', 'O',
       'P', 'PIJ', 'ZB', 'ZXZ'], dtype='<U4')

In [33]:
st1 = np.where(st == "AA")
st2 = np.where(st == "AB")
st3 = np.where(st == "AC")

print(st1)
print(st2)
print(st3)

(array([0], dtype=int64),)
(array([1], dtype=int64),)
(array([2], dtype=int64),)


# Day 13
Pandas